### ISSUE TITLE
Command order in Dynamics.R

### ISSUE THREAD

**Issue by mdzik** [CFD-GO/TCLB#112]
I found that Dynamics.R compilation is not working

this works fine:
```R
AddDensity( name="f[0]", dx= 0, dy= 0, group="f")
#....

AddDensity( name="h[0]", dx= 0, dy= 0, group="h")
#....

AddDensity( name="h_Z", dx=0, dy=0, group="HZ")

AddField( name="nw_x", stencil2d=1, group="nw")
AddField( name="nw_y", stencil2d=1, group="nw")
AddField("phi"      ,stencil2d=1 );

AddStage("BaseIteration", "Run", 
         load=DensityAll$group == "f" | DensityAll$group == "h"| DensityAll$group == "HZ",  
         save=Fields$group=="f" | Fields$group=="h" | Fields$group=="nw" | Fields$group == "HZ"
         ) 
AddStage("CalcPhi", 
         save=Fields$name=="phi" ,  
         load=DensityAll$group == "h"
         )
AddStage("BaseInit", "Init",  save=Fields$group=="f" | Fields$group=="h"| Fields$group == "HZ") 
AddStage("CalcWallNormall", "CalcNormal",   
         save=Fields$group=="nw",
         fixedPoint=TRUE
         ) 

AddAction("Iteration", c("BaseIteration","CalcPhi"))
AddAction("Init", c("BaseInit","CalcPhi", "CalcWallNormall"))

```

but if you change order, eq:
```R
AddDensity( name="f[0]", dx= 0, dy= 0, group="f")
#....

AddField( name="nw_x", stencil2d=1, group="nw") # <<<<<<<<

AddDensity( name="h[0]", dx= 0, dy= 0, group="h")
#....
AddDensity( name="h_Z", dx=0, dy=0, group="HZ")
```

solver brakes, and h_Z does not gets "advected" with zero-zero velocity through iterations.

Possible fixes:
1. fix the problem itself, but for AddStage it might require some sort of delayed compilation ;)
2. AddDensity called AFTER AddField should cause compilation error. This must be implemented for all Add* functions where order matters.

**Comment by llaniewski** [comment]
This is weird. They do completely independent things.

Do `SUMMARY` file differ in both cases? can you attach `SUMMARY.Rdata` from both cases here? (Attach files by dragging & dropping here)

**Comment by mdzik** [comment]
SUMMARY files + parto fo diff of whole CLB/xxx/*

```diff
% diff stage_ok stage_notok                                                                                                                                                                                    /tmp
diff stage_ok/Consts.h stage_notok/Consts.h
101c101
< #define FIELDS                                      10 
---
> #define FIELDS                                      11 
111c111,112
< #define  FIELDS_h_Z                                  9 
---
> #define  FIELDS_MyBad                                9 
> #define  FIELDS_h_Z                                 10 



```


[stage_notok.zip](https://github.com/CFD-GO/TCLB/files/641947/stage_notok.zip)
[stage_ok.zip](https://github.com/CFD-GO/TCLB/files/641950/stage_ok.zip)
[complete.diff.txt](https://github.com/CFD-GO/TCLB/files/641954/complete.diff.txt)

**Comment by mdzik** [comment]
do you want complete source?
btw: I "broke" the code, by adding field MyBad in "wrong" place, just before h_Z

**Comment by llaniewski** [comment]
Cannot yet reproduce. Is the model in any of your branches?
Are you working on [V6.1 RC]? I fixed an error related to recompilation: #113

**Comment by mdzik** [comment]
I don't think that is related to recompilation but will check. Problem persist with clean after rm -rf CLB/*.
branch: d2q9_thin_film. 

Add any field before h_Z, and use

[test.zip](https://github.com/CFD-GO/TCLB/files/642510/test.zip)

```bash
mdzik@itk2199:~/TCLB$ PYTHONPATH="/home/mdzik/TCLB_tools/Python:." CLB/d2q9_thin_film/main aperture.xml 
[  ] -------------------------------------------------------------------------
[  ] -  CLB version:    v6.0-beta-630-g885fdc1                               -
[  ] -        Model:            d2q9_thin_film                               -
[  ] -------------------------------------------------------------------------
[  ] Setting output path to: aperture
[ 0] WARNING: No "Units" element in config file
[  ] Mesh size in config file: 256x256x1
[  ] Global lattice size: 256x256x1
[  ] Max region size: 65536. Mesh size 65536. Overhead:  0%
[  ] Local lattice size: 256x256x1
[  ] [0] Cumulative allocation of 10534976 b (10.5 MB)
[  ] Creating geom size:65536
[  ] Setting output path to: aperture
[  ] loading geometry ...
[  ] Setting number of zones to 2
[  ] Setting BrinkmanHeightInv in zone  (-1) to 0.01 (0.010000)
[  ] Setting BrinkmanHeightInv in zone wet (1) to 0.03 (0.030000)
[  ] Initializing Lattice ...
[  ] Callback CallPython with no Iterations attribute====]  0s
[  ] Providing component h_Z to buffer..
[  ] ...provided h_Z
0.0415486236691 0.1
[  ] Result of Python call: 0
[  ] Setting action Solve at 1.000000 iterations
[  ]      0.0 MLBUps      0.00 GB/s [====================]
[  ] Callback CallPython with no Iterations attribute
/home/mdzik/bin/anaconda2/lib/python2.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/home/mdzik/bin/anaconda2/lib/python2.7/site-packages/IPython/frontend.py:21: ShimWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
  "All its subpackages have been moved to the top `IPython` level.", ShimWarning)
[  ] Providing component h_Z to buffer..
[  ] ...provided h_Z
WARNING: InteractiveShell.prompt_in1 is deprecated, use PromptManager.in_template
WARNING: InteractiveShell.prompt_out is deprecated, use PromptManager.out_template
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.


    
                     (          
                (    )\ )   (   
        (       )\  (()/( ( )\  
 `  )   )\ )  (((_)  /(_)))((_) 
 /(/(  (()/(  )\___ (_)) ((_)_  
((_)_\  )(_))((/ __|| |   | _ ) 
| '_ \)| || | | (__ | |__ | _ \ 
| .__/  \_, |  \___||____||___/ 
|_|     |__/                        
    

    example: 
    #cph is already definied for you :)
    
    Fx = cph.getScalar(0)
    Fy = cph.getVector(1)
    X,Y = cph.getXY(0)
    
    
CLB [1]> cph.getScalar(0)
CLB [1]: 
array([[ 0.06060348,  0.06148665,  0.06243412, ...,  0.0580127 ,
         0.05868155,  0.05937988],
       [ 0.06124171,  0.06211355,  0.06304797, ...,  0.05848529,
         0.05911463,  0.05977727],
       [ 0.06192706,  0.0627785 ,  0.06368573, ...,  0.05900154,
         0.05959438,  0.06022031],
       ..., 
       [ 0.06292109,  0.06397998,  0.06502877, ...,  0.07478733,
         0.07549911,  0.07620057],
       [ 0.06348421,  0.06449526,  0.06546819, ...,  0.07508769,
         0.07577075,  0.0764187 ],
       [ 0.06406403,  0.06502312,  0.06592019, ...,  0.07538209,
         0.07604828,  0.07665245]])

CLB [2]> 

```

if you add any field before H_z, last matrix will be only zeros

**Comment by mdzik** [comment]
aperture.xml has small syntax, sorry. Last <Solve is unnecessary

**Comment by llaniewski** [comment]
I think you have some unmerged things there:
https://github.com/mdzik/TCLB/blob/d2q9_thin_film/src/d2q9_thin_film/Dynamics.c.Rt#L42

**Comment by mdzik** [comment]
Ops, I forgot to push to github. I will do that on Monday: I don’t have
remote access to our network

2016-12-09 19:08 GMT+01:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by mdzik** [comment]
Updated

**Comment by llaniewski** [comment]
Ok. I identified where is the problem.

https://github.com/CFD-GO/TCLB/blob/v6.1_candidate/src/Lattice.cu.Rt#L960

It is a old debug function, which is not very good to use now. The field is probably streamed right, but it is not accessible by

```c++
void Lattice::Get_h_Z(real_t * tab)
{
        debug2("Pulling all h_Z\n");
        CudaMemcpy(
                tab,
                &Snaps[Snap].block14[ DENSITY_h_Z *region.sizeL()],
                region.sizeL()*sizeof(real_t),
                cudaMemcpyDeviceToHost);
} 
```

because it uses constant DENSITY_h_Z not FIELDS_h_Z.

There is a conceptual problem: Field is accessible only in directions allowed in Dynamics.R. So a field do not have to be accessible in the "direction" dx=0,dy=0,dz=0. In fact in most LBM schemes it is not. That's why it doesn't make sense in current version of the code to say Get_f2, because we don't have all the information. Saying in terms of LBM; should it return the f2 after or before streaming?

We have to discuss it.

What should be available to Python? pre- or post- streaming values. What should be outputed by Python? should output from python be treated like output from collision? or should it be only a modification of already existing values?

Changing the https://github.com/CFD-GO/TCLB/blob/v6.1_candidate/src/Lattice.cu.Rt#L943 loop to a loop over Fields, would hot-fix the issue, but will not give right values on boundaries (and in parallel would bring death upon us all).

**Comment by mdzik** [comment]
Regarding python: we need a bi-directional (not necessary same variable)
way to transfer data from/to python. Py can handle any data chunk in form
of C array without additional allocation.
Current state:
"quantities" are used to transfer data FROM CLB (like velocity) to Py
"densities" with streaming velocity 0, is used to transfer data TO CLB
(like some local Velocity-dependent parameters, eq. values to be used in
BC, calculated from Velocity field in whole domain)

I don't think I use fields in python context at all.

BUT

If you add ANY field before zero-velocity density, things got messed up,
and this pseudo-density does not get streamed.

Other thing is that some times it could be beneficial to define read-only
variable, that is written by python or during initialization, like mid-link
field for bounce-back.


If we are not on the same page, we need PhO to process it :]







2016-12-12 19:46 GMT+01:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by llaniewski** [comment]
Ok, the problem should be solved by https://github.com/llaniewski/TCLB/commit/c51e2d0f6260edd27624f688d5c0b06a29908c99

Based on what you said, I decided that the best way to go is to use the existing 'parameter' mechanism, as it will be somewhat consistent with the adjoint things. You can specify parameter=TRUE for any density which has streaming dx=0,dy=0,dz=0. This is mainly used for the means of topology optimization now - but I think it is a good idea to use it also for your Python integration.

You should be able to test it in your pre-v6.1 version by cherrypicking:
```bash
git remote add llaniewski https://github.com/llaniewski/TCLB.git
git fetch llaniewski
git cherry-pick c51e2d0f6260edd27624f688d5c0b06a29908c99
test the hell out of it :-)
```

For the densities which you want to pass from python, you have to use
```R
AddDensity( name="h_Z", group="HZ", parameter=TRUE )
```

If it will work, please comment here. Then we'll decide what to do with some of the tests (for instance in d2q9_kuper you read f0 - which is 0-streamed, but it is hardly a parameter.)

**comment**:
I still think that everything is fine with streaming, the only problem is the Get_ Set_ Clear_ functions. In the case you're describing, when you add "MyBad" field, it causes `FIELDS_h_Z != DENSITY_h_Z`, and the wrong implementation of Set_h_Z was setting the wrong field, and as the result, you ended up with the wrong h_Z. It was streamed right, but it was not set by the Set_ function.

**Comment by mdzik** [comment]
OK, seems good and tidy. I will check it ASAP.


> *comment*:
> I still think that everything is fine with streaming, the only problem is
> the Get_ Set_ Clear_ functions. In the case you're describing, when you add
> "MyBad" field, it causes FIELDS_h_Z != DENSITY_h_Z, and the wrong
> implementation of Set_h_Z was setting the wrong field, and as the result,
> you ended up with the wrong h_Z. It was streamed right, but it was not set
> by the Set_ function.
>

You're The Knowledge Keeper ;)
Just for completeness: I've checked, also following scenario:
1. Init
2. Python (Get_, Set_ used by CLB ?? )
2.b SOLVE, iterations=1
3. Python again, (Get_),  check h_Z

if SOLVE (2.b) is present, h_Z is empty
if SOLVE (2.b) is NOT present, h_Z is OK

**Comment by llaniewski** [comment]
This is because the h_Z is being set, but in a wrong place - in the place of 'MyBad' (because the DENSITY_h_Z constant is wrong). Then if you **immediately** read it from the same wrong place, then it is ok, but if you add SOLVE with 1 iteration, then there is no streaming for MyBad, and in the next iteration it is empty. Then when you try to read h_Z, you really read MyBad which is empty.

After this correction, the Get_ Set_ Clear_ functions use the FIELDS_ constants, so they will always read/write the right field.

**Comment by mdzik** [comment]
OK, now I got it.

Part that I still don't get, is why command order in Dynamics.R change
that. Why DENSITY_h_Z points where it should only if there is no field in
between densities?
One think is to clear the logic behind data exchange, other thing is
"determinism" of Dynamics.R rendering.
If order must matter, then we need to add some sort of sections, or compile
error to prevent undetermined behaviour.

**Comment by llaniewski** [comment]
The problem is that DENSITY_h_Z should never be used to calculate the offset - and it was used in Get_ Set_ etc. Only FIELDS_ constants can be used as such. So the only problem was that there was an error in Set_ Get_ functions.

The order in Density.R doesn't make a difference (and it shouldn't). The error in the Get_ Set_ code just wasn't visible until you made this order change in Density.R (because DENSITY_ and FIELDS_ constants were the same in such case).

**Comment by llaniewski** [comment]
Closed by #117 ?

**Comment by mdzik** [comment]
Verified
